# Generated by Django 4.1.7 on 2023-02-14 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('real_name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='images')),
                ('superpowers', models.TextField()),
                ('desc', models.TextField()),
                ('quantity', models.IntegerField(default=0)),
                ('numbers', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Heroes',
            },
        ),
        migrations.CreateModel(
            name='Universe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('img', models.ImageField(upload_to='images')),
            ],
            options={
                'verbose_name_plural': 'Universal',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rating', models.FloatField()),
                ('text', models.TextField()),
                ('hero', models.ManyToManyField(to='Reviews.hero')),
            ],
        ),
        migrations.AddField(
            model_name='hero',
            name='universe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reviews.universe'),
        ),
    ]
