# Generated by Django 4.1.7 on 2023-02-15 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reviews', '0002_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='slug',
            field=models.SlugField(default='index', max_length=100),
            preserve_default=False,
        ),
    ]
