# Generated by Django 4.1.7 on 2023-02-15 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reviews', '0003_hero_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero',
            name='slug',
        ),
    ]
