# Generated by Django 4.1.7 on 2023-02-22 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reviews', '0004_remove_hero_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='universe',
            options={'verbose_name_plural': 'Universes'},
        ),
    ]
